# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_conversation_detect_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='confidence_person',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='context',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='detect_sentiment',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='district',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='grade_section',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='problem_location',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sentiment_value',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='violence_type',
        ),
        migrations.AddField(
            model_name='conversation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
