# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180122_2312'),
        ('orders', '0003_auto_20180122_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='addons',
            field=models.ManyToManyField(to='products.ProductAddon'),
        ),
    ]
