# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created'],
                'default_permissions': ('add', 'change', 'delete', 'get', 'list', 'patch'),
            },
        ),
        migrations.CreateModel(
            name='ProductAddonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=100)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_categories', to='products.ProductCategory')),
            ],
            options={
                'ordering': ['-created'],
                'default_permissions': ('add', 'change', 'delete', 'get', 'list', 'patch'),
            },
        ),
        migrations.AddField(
            model_name='productaddon',
            name='addon_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='products.ProductAddonCategory'),
        ),
    ]
